app:
  name: task-xxl-job
  id: task-xxl-job
# web port
server:
  port: 8180
# no web
#spring.main.web-environment=false

#定时作业
xxl:
  job:
    admin:
      addresses: http://10.190.83.199:8080/xxl-job-admin
    executor:
      logpath: /data/applogs/xxl-job/jobhandler
      appname: ${app.name}
      port: 8181
      logretentiondays: -1
      ip:
    accessToken:

# log config
logging:
  config: classpath:logback.xml